pipeline:
  build:
    image: node:8
    commands:
      - yarn
      - yarn build
  tests:
    image: node:8
    commands:
      - yarn install
      - yarn run lint
      - yarn run test:unit
  sonar:
    image: aosapps/drone-sonar-plugin
    commands:
      - echo $PWD
      - sonar-scanner -Dsonar.login=$${SONAR_LOGIN}
    secrets: [SONAR_LOGIN]
    when:
      event: push
  publish:
    image: plugins/npm
    settings:
      token: $${NPM_LOGIN}
    secrets: [NPM_LOGIN]
    when:
      event: push
