name: Lint
on: [push]

jobs:
  test:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run install
        run: yarn
      - name: Run linting
        run: yarn lint
